# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'AUIKitVoiceRoom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AUIKitVoiceRoom
  pod 'AScenesKit', :path => '../AScenesKit'
  pod 'AUIKit', :path => '../../AUIKit/iOS'
  pod 'AgoraRtcEngine_iOS', :path => './libs'
  pod 'AgoraLyricsScore', '1.1.1-beta-3'

end
